eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8893
spring:
  application:
    name: config-server
  #本地配置
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

  #git拉配置
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/FunriLy/springcloud-study/
#          search-paths: config-repo
#          username: UserName
#          password: Password








