eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8892
spring:
  application:
    name: zuul
zuul:
  ignored-services: "*"
  routes:
    a:
      path: /api/a/**
      serviceId: ribbon
    b:
      path: /api/b/**
      serviceId: feign


